name: pawpal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  http: ^1.6.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
